"""Seed catalogue definitions.

Fabric images are rendered by swatches.py rather than downloaded, so every
seed record ships with a licence we actually hold ("BB Apparel — generated
asset"). Real fabric photography is added afterwards through the admin
uploader or the reviewed web importer, which record source_url, source_name
and licence for each image.

`swatch` describes how to render the seed image; it is kept on the record so a
seed fabric can be re-rendered deterministically after a volume is wiped.
"""

SEED_FABRICS = [
    {
        "id": "fab_ankara_royal_geo",
        "name": "Royal Blue Geometric Ankara",
        "category": "Ankara",
        "subcategory": "Wax Print",
        "pattern_type": "geometric",
        "description": "Bold diamond motif wax print in royal blue with red and gold accents — the everyday celebration fabric.",
        "texture_description": "Crisp cotton wax print with a firm hand and a matte finish.",
        "tags": ["Traditional", "Contemporary", "Bold"],
        "region": "West Africa",
        "swatch": {"kind": "geometric", "palette": ["#123a75", "#c62f2f", "#d8a63c"], "options": {"motif": "diamond"}},
    },
    {
        "id": "fab_ankara_emerald_bloom",
        "name": "Emerald Bloom Ankara",
        "category": "Ankara",
        "subcategory": "Wax Print",
        "pattern_type": "floral",
        "description": "Emerald ground scattered with coral and saffron blooms — soft enough for daywear, rich enough for owambe.",
        "texture_description": "Smooth cotton wax print, medium weight.",
        "tags": ["Floral", "Contemporary"],
        "region": "West Africa",
        "swatch": {"kind": "floral", "palette": ["#0f4d3a", "#e0678a", "#f0c94b", "#1d7a52"], "options": {}},
    },
    {
        "id": "fab_ankara_sunset_ring",
        "name": "Sunset Ring Ankara",
        "category": "Ankara",
        "subcategory": "Wax Print",
        "pattern_type": "geometric",
        "description": "Concentric rings in sunset amber and deep teal, printed at a generous scale for gowns and agbada.",
        "texture_description": "Cotton wax print with a lightly waxed sheen.",
        "tags": ["Bold", "Contemporary"],
        "region": "West Africa",
        "swatch": {"kind": "geometric", "palette": ["#0d4c52", "#e2762d", "#f2c14e"], "options": {"motif": "circle"}},
    },
    {
        "id": "fab_adire_indigo_eleko",
        "name": "Indigo Adire Eleko",
        "category": "Adire",
        "subcategory": "Resist Dye",
        "pattern_type": "abstract",
        "description": "Hand-resist indigo with ringed motifs and folded bands, in the Yoruba adire eleko tradition.",
        "texture_description": "Soft washed cotton, slightly irregular dye depth.",
        "tags": ["Traditional", "Handmade"],
        "region": "South-West Nigeria",
        "swatch": {"kind": "adire", "palette": ["#1b3560", "#dfe6f2"], "options": {}},
    },
    {
        "id": "fab_adire_slate_wave",
        "name": "Slate Adire Wave",
        "category": "Adire",
        "subcategory": "Resist Dye",
        "pattern_type": "abstract",
        "description": "Muted slate resist dye with a looser, more contemporary ring layout.",
        "texture_description": "Lightweight cotton with a lived-in drape.",
        "tags": ["Contemporary", "Handmade"],
        "region": "South-West Nigeria",
        "swatch": {"kind": "adire", "palette": ["#3d4a55", "#e6ebef"], "options": {"seed": 9}},
    },
    {
        "id": "fab_lace_ivory_chantilly",
        "name": "Ivory Corded Lace",
        "category": "Lace",
        "subcategory": "Corded",
        "pattern_type": "floral",
        "description": "Fine ivory net with corded floral medallions — the classic choice for buba and occasion gowns.",
        "texture_description": "Sheer net ground with raised corded motifs.",
        "tags": ["Occasion", "Traditional"],
        "region": "Import",
        "swatch": {"kind": "lace", "palette": ["#f2ede4", "#c9b48a"], "options": {}},
    },
    {
        "id": "fab_lace_gold_cord",
        "name": "Gold Cord Lace",
        "category": "Lace",
        "subcategory": "Corded",
        "pattern_type": "floral",
        "description": "Champagne net worked with gold cording — heavier and more formal than plain French lace.",
        "texture_description": "Dense corded lace with a soft metallic gleam.",
        "tags": ["Occasion", "Embroidered"],
        "region": "Import",
        "swatch": {"kind": "lace", "palette": ["#e8d7ae", "#a5822f"], "options": {"seed": 21}},
    },
    {
        "id": "fab_brocade_burgundy_damask",
        "name": "Burgundy Damask Brocade",
        "category": "Brocade",
        "subcategory": "Damask",
        "pattern_type": "floral",
        "description": "Tonal burgundy damask woven with a gold-lit motif — structured enough to hold an agbada shape.",
        "texture_description": "Firm jacquard weave with a satin-faced motif.",
        "tags": ["Traditional", "Occasion"],
        "region": "West Africa",
        "swatch": {"kind": "damask", "palette": ["#6c202e", "#c6a04a"], "options": {}},
    },
    {
        "id": "fab_brocade_midnight_gold",
        "name": "Midnight Gold Brocade",
        "category": "Brocade",
        "subcategory": "Damask",
        "pattern_type": "floral",
        "description": "Near-black ground with an antique gold damask motif for evening senator and kaftan looks.",
        "texture_description": "Heavy jacquard with a low sheen.",
        "tags": ["Occasion", "Contemporary"],
        "region": "West Africa",
        "swatch": {"kind": "damask", "palette": ["#161a24", "#b8933f"], "options": {"seed": 4}},
    },
    {
        "id": "fab_atiku_sky_cotton",
        "name": "Sky Atiku Cotton",
        "category": "Atiku",
        "subcategory": "Suiting",
        "pattern_type": "textured",
        "description": "Pale sky atiku with the fine dry weave that makes native two-piece sets sit cleanly.",
        "texture_description": "Dry-handed cotton suiting with a fine slub.",
        "tags": ["Traditional", "Everyday"],
        "region": "West Africa",
        "swatch": {"kind": "solid", "palette": ["#a8c0d8"], "options": {"texture": "linen"}},
    },
    {
        "id": "fab_atiku_sand",
        "name": "Sand Atiku",
        "category": "Atiku",
        "subcategory": "Suiting",
        "pattern_type": "textured",
        "description": "Warm sand atiku — the safest ground for heavy embroidery on kaftan and agbada.",
        "texture_description": "Soft matte suiting with a visible slub.",
        "tags": ["Traditional", "Everyday"],
        "region": "West Africa",
        "swatch": {"kind": "solid", "palette": ["#c8b48a"], "options": {"texture": "linen"}},
    },
    {
        "id": "fab_senator_charcoal",
        "name": "Charcoal Senator Weave",
        "category": "Senator",
        "subcategory": "Suiting",
        "pattern_type": "solid",
        "description": "Charcoal senator-weight cloth with a smooth face — the default for formal senator sets.",
        "texture_description": "Fine, smooth suiting with a dry matte finish.",
        "tags": ["Formal", "Contemporary"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#3a3d42"], "options": {"texture": "plain"}},
    },
    {
        "id": "fab_senator_navy",
        "name": "Navy Senator Weave",
        "category": "Senator",
        "subcategory": "Suiting",
        "pattern_type": "solid",
        "description": "Deep navy senator cloth, the most requested colour for wedding-guest sets.",
        "texture_description": "Smooth suiting with a slight body.",
        "tags": ["Formal", "Contemporary"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#20304f"], "options": {"texture": "plain"}},
    },
    {
        "id": "fab_silk_champagne",
        "name": "Champagne Silk Charmeuse",
        "category": "Silk",
        "subcategory": "Charmeuse",
        "pattern_type": "solid",
        "description": "Liquid champagne silk with a bright face and fluid drape — for bubu and long gowns.",
        "texture_description": "High-sheen satin face, very fluid.",
        "tags": ["Occasion", "Contemporary"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#d8c49a"], "options": {"texture": "silk"}},
    },
    {
        "id": "fab_chiffon_blush",
        "name": "Blush Chiffon",
        "category": "Chiffon",
        "subcategory": "Sheer",
        "pattern_type": "solid",
        "description": "Airy blush chiffon for layered gowns and flowing sleeves.",
        "texture_description": "Sheer, dry and very light.",
        "tags": ["Occasion", "Contemporary"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#e6c9c4"], "options": {"texture": "chiffon"}},
    },
    {
        "id": "fab_velvet_plum",
        "name": "Deep Plum Velvet",
        "category": "Velvet",
        "subcategory": "Pile",
        "pattern_type": "solid",
        "description": "Rich plum velvet with a deep pile — heavy, formal, and it photographs beautifully.",
        "texture_description": "Dense short pile with a directional sheen.",
        "tags": ["Occasion", "Formal"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#4a1f3d"], "options": {"texture": "velvet"}},
    },
    {
        "id": "fab_linen_natural",
        "name": "Natural Linen",
        "category": "Linen",
        "subcategory": "Plain Weave",
        "pattern_type": "textured",
        "description": "Undyed natural linen with an honest slub — the coolest option for daytime kaftan.",
        "texture_description": "Crisp dry weave with irregular yarn thickness.",
        "tags": ["Everyday", "Contemporary"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#d9cdb4"], "options": {"texture": "linen"}},
    },
    {
        "id": "fab_cotton_ivory_poplin",
        "name": "Ivory Cotton Poplin",
        "category": "Cotton",
        "subcategory": "Poplin",
        "pattern_type": "solid",
        "description": "Clean ivory poplin — a neutral ground that lets embroidery and beading do the talking.",
        "texture_description": "Smooth, tightly woven cotton.",
        "tags": ["Everyday", "Formal"],
        "region": "Import",
        "swatch": {"kind": "solid", "palette": ["#efe9db"], "options": {"texture": "plain"}},
    },
    {
        "id": "fab_denim_indigo",
        "name": "Classic Indigo Denim",
        "category": "Denim",
        "subcategory": "Twill",
        "pattern_type": "textured",
        "description": "Mid-weight indigo denim twill for contemporary native-cut sets.",
        "texture_description": "Diagonal twill with indigo depth variation.",
        "tags": ["Contemporary", "Everyday"],
        "region": "Import",
        "swatch": {"kind": "twill", "palette": ["#2f4f7a"], "options": {}},
    },
    {
        "id": "fab_asooke_royal_stripe",
        "name": "Aso-Oke Royal Stripe",
        "category": "Traditional",
        "subcategory": "Aso-Oke",
        "pattern_type": "striped",
        "description": "Hand-woven strip cloth in royal blue and gold, crossed by fine warp bars.",
        "texture_description": "Coarse hand-loom weave with visible strip joins.",
        "tags": ["Traditional", "Occasion", "Handmade"],
        "region": "South-West Nigeria",
        "swatch": {"kind": "aso_oke", "palette": ["#1b3560", "#c6a04a", "#e8dbbd"], "options": {}},
    },
    {
        "id": "fab_embroidered_black_gold",
        "name": "Black Guinea with Gold Embroidery",
        "category": "Embroidered",
        "subcategory": "Guinea Brocade",
        "pattern_type": "geometric",
        "description": "Black guinea brocade worked with radiating gold embroidery — the classic agbada treatment.",
        "texture_description": "Firm brocade ground with raised satin-stitch motifs.",
        "tags": ["Traditional", "Occasion", "Embroidered"],
        "region": "West Africa",
        "swatch": {"kind": "embroidered", "palette": ["#101820", "#c6a04a"], "options": {}},
    },
    {
        "id": "fab_check_burgundy",
        "name": "Burgundy Windowpane Check",
        "category": "Contemporary",
        "subcategory": "Check",
        "pattern_type": "checked",
        "description": "Burgundy and cream windowpane check for modern tunics and skirt-and-blouse sets.",
        "texture_description": "Yarn-dyed check on a soft matte ground.",
        "tags": ["Contemporary", "Everyday"],
        "region": "Import",
        "swatch": {"kind": "checks", "palette": ["#6c202e", "#e8dbbd"], "options": {}},
    },
]


SEED_OUTFITS = [
    {
        "id": "out_modern_senator",
        "name": "Modern Senator",
        "category": "Men",
        "template_id": "modern-senator",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Mandarin-collar top with a straight five-button placket over matching trousers.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "tailored senator set with a mandarin collar, straight placket and matching trousers, clean pressed finish",
        "sort_order": 10,
    },
    {
        "id": "out_classic_kaftan",
        "name": "Classic Kaftan",
        "category": "Men",
        "template_id": "classic-kaftan",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Full-length flowing kaftan with wide sleeves and a short mandarin placket.",
        "supported_regions": ["Nigeria", "West Africa", "North Africa"],
        "default_prompt": "full length kaftan robe with wide sleeves and a mandarin collar, relaxed drape",
        "sort_order": 20,
    },
    {
        "id": "out_grand_agbada",
        "name": "Grand Agbada",
        "category": "Men",
        "template_id": "grand-agbada",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Three-piece agbada — wide flowing outer robe over an inner tunic and trousers.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "grand agbada with a wide flowing outer robe over a matching tunic and trousers, ceremonial drape",
        "sort_order": 30,
    },
    {
        "id": "out_native_two_piece",
        "name": "Native Two-Piece",
        "category": "Men",
        "template_id": "native-two-piece",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Short-sleeve native top with a round neck over matching trousers.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "short sleeve native two piece set, round neck top and matching trousers",
        "sort_order": 40,
    },
    {
        "id": "out_long_tunic",
        "name": "Long Tunic",
        "category": "Men",
        "template_id": "long-tunic",
        "garment_type": "tops",
        "mask_type": "upper_body",
        "description": "Knee-length tunic with a mandarin collar — worn over trousers or jeans.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "long tunic shirt with a mandarin collar, straight cut, worn over trousers",
        "sort_order": 50,
    },
    {
        "id": "out_ankara_gown",
        "name": "Ankara Gown",
        "category": "Women",
        "template_id": "ankara-gown",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Fitted bodice flaring into a full floor-length skirt.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "fitted ankara gown with a defined waist and a full floor length skirt",
        "sort_order": 60,
    },
    {
        "id": "out_long_gown",
        "name": "Long Gown",
        "category": "Women",
        "template_id": "long-gown",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Column gown with long sleeves and a soft V neckline.",
        "supported_regions": ["Nigeria", "West Africa", "Import"],
        "default_prompt": "long column gown with full length sleeves and a soft v neckline, fluid drape",
        "sort_order": 70,
    },
    {
        "id": "out_iro_and_buba",
        "name": "Iro and Buba",
        "category": "Women",
        "template_id": "iro-and-buba",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Wide-sleeved buba blouse over a wrapped iro skirt.",
        "supported_regions": ["South-West Nigeria"],
        "default_prompt": "iro and buba: a wide sleeved buba blouse over a wrapped iro skirt, traditional Yoruba styling",
        "sort_order": 80,
    },
    {
        "id": "out_skirt_and_blouse",
        "name": "Skirt and Blouse",
        "category": "Women",
        "template_id": "skirt-and-blouse",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Neat blouse with a long straight skirt — office to owambe.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "matching skirt and blouse set, neat fitted blouse with a long straight skirt",
        "sort_order": 90,
    },
    {
        "id": "out_peplum_set",
        "name": "Peplum Top and Skirt",
        "category": "Women",
        "template_id": "peplum-top",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Structured peplum top with a long fitted skirt.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "structured peplum top with a flared waist over a long fitted skirt",
        "sort_order": 100,
    },
    {
        "id": "out_bubu",
        "name": "Bubu Boubou",
        "category": "Women",
        "template_id": "bubu-boubou",
        "garment_type": "one-pieces",
        "mask_type": "full_body",
        "description": "Voluminous free-flowing boubou with dropped sleeves.",
        "supported_regions": ["Nigeria", "West Africa"],
        "default_prompt": "voluminous free flowing boubou gown with dropped wide sleeves",
        "sort_order": 110,
    },
]

FABRIC_CATEGORIES = [
    "Ankara", "Lace", "Adire", "Atiku", "Senator", "Brocade", "Silk", "Chiffon",
    "Velvet", "Linen", "Cotton", "Denim", "Traditional", "Embroidered", "Contemporary",
]

PATTERN_TYPES = [
    "solid", "striped", "checked", "geometric", "floral", "dotted", "abstract", "textured",
]

OUTFIT_CATEGORIES = ["Men", "Women", "Unisex"]

SEED_LICENSE = {
    "source_name": "BB Apparel",
    "source_url": "",
    "license": "BB Apparel — generated asset (owned, unrestricted internal use)",
    "attribution": "Swatch generated procedurally by BB Apparel Fabric Studio.",
}
